import React, { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { toast } from "react-toastify";
import {
  clearAllApplicationErrors,
  resetApplicationSlice,
  deleteApplication,
  fetchJobSeekerApplications,
} from "../store/slices/applicationSlice";
import Spinner from "../components/Spinner";
import jsPDF from "jspdf";
import "jspdf-autotable";
import {
  FaFile,
  FaTrash,
  FaDownload,
  FaBriefcase,
  FaEye,
} from "react-icons/fa";
import { motion, AnimatePresence } from "framer-motion";

// Logo as base64 (replace with your actual logo if needed)
const logoBase64 =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40' viewBox='0 0 24 24' fill='%231B1D3E'%3E%3Cpath d='M20 6h-4V4c0-1.1-.9-2-2-2h-4c-1.1 0-2 .9-2 2v2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zM10 4h4v2h-4V4zm10 16H4V8h16v12z'/%3E%3C/svg%3E";

const MyApplications = () => {
  const dispatch = useDispatch();
  const { applications, loading, error, message } = useSelector(
    (state) => state.applications,
  );

  useEffect(() => {
    dispatch(fetchJobSeekerApplications());
  }, [dispatch]);

  useEffect(() => {
    if (error) {
      toast.error(error);
      dispatch(clearAllApplicationErrors());
    }
    if (message) {
      toast.success(message);
      dispatch(resetApplicationSlice());
      dispatch(fetchJobSeekerApplications());
    }
  }, [dispatch, error, message]);

  const handleDeleteApplication = async (id) => {
    if (window.confirm("Are you sure you want to delete this application?")) {
      await dispatch(deleteApplication(id));
      dispatch(fetchJobSeekerApplications());
    }
  };

  const handleDownloadApplication = (app) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Add logo
    try {
      doc.addImage(logoBase64, "SVG", 14, 10, 20, 20);
    } catch {
      doc.setFillColor(27, 29, 62);
      doc.rect(14, 10, 20, 20, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(12);
      doc.text("JP", 20, 22);
      doc.setTextColor(0, 0, 0);
    }

    // Header
    doc.setFontSize(20);
    doc.setTextColor(27, 29, 62);
    doc.text("JobPortal", 40, 22);
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text("Application Details", 40, 30);

    doc.setDrawColor(27, 29, 62);
    doc.line(14, 35, pageWidth - 14, 35);

    // Applicant Info
    doc.setFontSize(14);
    doc.setTextColor(27, 29, 62);
    doc.text("Applicant Information", 14, 45);
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(`Name: ${app.jobSeekerInfo.name}`, 14, 55);
    doc.text(`Email: ${app.jobSeekerInfo.email}`, 14, 62);
    doc.text(`Phone: ${app.jobSeekerInfo.phone}`, 14, 69);
    doc.text(`Address: ${app.jobSeekerInfo.address}`, 14, 76);

    // Job Info
    doc.setFontSize(14);
    doc.setTextColor(27, 29, 62);
    doc.text("Job Information", 14, 90);
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(`Job Title: ${app.jobInfo.jobTitle}`, 14, 100);
    doc.text(`Company: ${app.jobInfo.CompanyName}`, 14, 107);
    doc.text(`Location: ${app.jobInfo.location || "N/A"}`, 14, 114);
    doc.text(`Salary: ${app.jobInfo.salary || "N/A"}`, 14, 121);

    // Cover Letter
    doc.setFontSize(14);
    doc.setTextColor(27, 29, 62);
    doc.text("Cover Letter", 14, 135);
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const splitCover = doc.splitTextToSize(
      app.jobSeekerInfo.coverLetter || "No cover letter provided",
      pageWidth - 28,
    );
    doc.text(splitCover, 14, 145);

    // Status and Dates
    const finalY = 145 + splitCover.length * 5;
    doc.setFontSize(14);
    doc.setTextColor(27, 29, 62);
    doc.text("Application Status", 14, finalY + 5);
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(`Status: ${app.status}`, 14, finalY + 15);
    doc.text(
      `Applied on: ${new Date(app.appliedAt || Date.now()).toLocaleDateString()}`,
      14,
      finalY + 22,
    );
    doc.text(
      `Application expires: ${new Date(app.jobInfo.expiryDate).toLocaleDateString()}`,
      14,
      finalY + 29,
    );

    // Footer
    doc.setDrawColor(27, 29, 62);
    doc.line(
      14,
      doc.internal.pageSize.getHeight() - 20,
      pageWidth - 14,
      doc.internal.pageSize.getHeight() - 20,
    );
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "Generated by JobPortal",
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" },
    );

    doc.save(`Application_${app._id}.pdf`);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-8"
        >
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">
            My <span className="text-[#1B1D3E]">Applications</span>
          </h1>
          <p className="text-gray-600">
            Track and manage your job applications
          </p>
        </motion.div>

        {loading ? (
          <div className="flex justify-center p-12">
            <Spinner />
          </div>
        ) : applications.length === 0 ? (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-center py-16 bg-white rounded-2xl shadow-sm border border-gray-100"
          >
            <FaBriefcase className="mx-auto h-12 w-12 text-gray-400 mb-4" />
            <h3 className="text-xl font-medium text-gray-900 mb-2">
              No applications yet
            </h3>
            <p className="text-gray-500">
              Start applying to jobs and they'll appear here.
            </p>
          </motion.div>
        ) : (
          <>
            {/* Desktop Table with Borders */}
            <div className="hidden lg:block overflow-x-auto bg-white rounded-2xl shadow-xl border border-gray-200">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-[#1B1D3E]">
                    <th className="px-6 py-4 text-left text-sm font-semibold text-white border border-[#1B1D3E]">
                      Job Title
                    </th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-white border border-[#1B1D3E]">
                      Company
                    </th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-white border border-[#1B1D3E]">
                      Applicant
                    </th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-white border border-[#1B1D3E]">
                      Status
                    </th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-white border border-[#1B1D3E]">
                      Expires
                    </th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-white border border-[#1B1D3E]">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  <AnimatePresence>
                    {applications.map((app, index) => (
                      <motion.tr
                        key={app._id}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -10 }}
                        transition={{ delay: index * 0.05 }}
                        className="hover:bg-gray-50 transition-colors"
                      >
                        <td className="px-6 py-4 border border-gray-200 font-medium text-gray-900">
                          {app.jobInfo.jobTitle}
                        </td>
                        <td className="px-6 py-4 border border-gray-200 text-gray-700">
                          {app.jobInfo.CompanyName}
                        </td>
                        <td className="px-6 py-4 border border-gray-200 text-gray-700">
                          {app.jobSeekerInfo.name}
                        </td>
                        <td className="px-6 py-4 border border-gray-200 text-center">
                          <span
                            className={`inline-flex px-3 py-1 rounded-full text-xs font-semibold ${
                              app.status === "pending"
                                ? "bg-yellow-100 text-yellow-800"
                                : app.status === "accepted"
                                  ? "bg-green-100 text-green-800"
                                  : "bg-red-100 text-red-800"
                            }`}
                          >
                            {app.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 border border-gray-200 text-center text-gray-600">
                          {new Date(
                            app.jobInfo.expiryDate,
                          ).toLocaleDateString()}
                        </td>
                        <td className="px-6 py-4 border border-gray-200">
                          <div className="flex flex-col gap-2 items-center">
                            <ActionButton
                              label="Resume"
                              Icon={FaFile}
                              onClick={() =>
                                window.open(
                                  app.jobSeekerInfo.resume?.url,
                                  "_blank",
                                )
                              }
                              color="blue"
                            />
                            <ActionButton
                              label="PDF"
                              Icon={FaDownload}
                              onClick={() => handleDownloadApplication(app)}
                              color="blue"
                            />
                            <ActionButton
                              label="Delete"
                              Icon={FaTrash}
                              onClick={() => handleDeleteApplication(app._id)}
                              color="red"
                            />
                          </div>
                        </td>
                      </motion.tr>
                    ))}
                  </AnimatePresence>
                </tbody>
              </table>
            </div>

            {/* Mobile Card View */}
            <div className="lg:hidden grid grid-cols-1 md:grid-cols-2 gap-6">
              <AnimatePresence>
                {applications.map((app) => (
                  <motion.div
                    key={app._id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    transition={{ duration: 0.3 }}
                    className="bg-white rounded-xl shadow-md hover:shadow-lg transition-shadow border border-gray-200 overflow-hidden"
                  >
                    <div className="p-5">
                      <div className="flex items-start justify-between mb-3">
                        <div>
                          <h3 className="font-bold text-lg text-gray-900">
                            {app.jobInfo.jobTitle}
                          </h3>
                          <p className="text-sm text-gray-600">
                            {app.jobInfo.CompanyName}
                          </p>
                        </div>
                        <span
                          className={`px-3 py-1 rounded-full text-xs font-semibold ${
                            app.status === "pending"
                              ? "bg-yellow-100 text-yellow-800"
                              : app.status === "accepted"
                                ? "bg-green-100 text-green-800"
                                : "bg-red-100 text-red-800"
                          }`}
                        >
                          {app.status}
                        </span>
                      </div>

                      <div className="space-y-2 text-sm text-gray-600 mb-4">
                        <p>
                          <span className="font-medium">Applicant:</span>{" "}
                          {app.jobSeekerInfo.name}
                        </p>
                        <p>
                          <span className="font-medium">Expires:</span>{" "}
                          {new Date(
                            app.jobInfo.expiryDate,
                          ).toLocaleDateString()}
                        </p>
                      </div>

                      <div className="flex flex-col gap-2">
                        <ActionButton
                          label="View Resume"
                          Icon={FaEye}
                          onClick={() =>
                            window.open(app.jobSeekerInfo.resume?.url, "_blank")
                          }
                          color="blue"
                          fullWidth
                        />
                        <ActionButton
                          label="Download PDF"
                          Icon={FaDownload}
                          onClick={() => handleDownloadApplication(app)}
                          color="blue"
                          fullWidth
                        />
                        <ActionButton
                          label="Delete"
                          Icon={FaTrash}
                          onClick={() => handleDeleteApplication(app._id)}
                          color="red"
                          fullWidth
                        />
                      </div>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

// Reusable action button component with enhanced styling
const ActionButton = ({
  label,
  Icon,
  onClick,
  color = "blue",
  fullWidth = false,
}) => {
  const colorClasses = {
    blue: "bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200",
    red: "bg-red-50 hover:bg-red-100 text-red-700 border border-red-200",
  };
  return (
    <motion.button
      whileHover={{ scale: 1.03 }}
      whileTap={{ scale: 0.98 }}
      onClick={onClick}
      className={`${colorClasses[color]} font-medium py-2 px-4 rounded-lg flex items-center justify-center gap-2 transition-all shadow-sm hover:shadow ${
        fullWidth ? "w-full" : "w-32"
      }`}
      title={label}
    >
      <Icon className="w-4 h-4" />
      <span className="text-sm">{label}</span>
    </motion.button>
  );
};

export default MyApplications;
